branch-defaults:
  main:
    environment: node-env
    group_suffix: null
environment-defaults:
  node-test:
    branch: null
    repository: null
global:
  application_name: back
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
